# Generated by Django 4.1.3 on 2023-08-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("msg_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(default="", max_length=70)),
                ("subject", models.CharField(default="", max_length=70)),
                ("message", models.TextField(default="", max_length=700)),
            ],
        ),
    ]
