# Generated by Django 4.1.3 on 2023-10-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codem", "0002_hackathon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("filter", models.CharField(max_length=200)),
                ("logo_image", models.ImageField(upload_to="")),
                ("description", models.TextField()),
            ],
        ),
    ]
