# Generated by Django 4.1.3 on 2023-10-02 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("codem", "0003_portfolio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Portfolio",
        ),
    ]
