# Generated by Django 4.1.3 on 2023-11-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codem", "0004_delete_portfolio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
