# Generated by Django 4.1.3 on 2023-11-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codem", "0005_tool"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="link",
            field=models.URLField(default=""),
        ),
    ]
