# Generated by Django 4.1.3 on 2023-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codem", "0006_tool_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                ("description", models.TextField()),
                ("link", models.URLField()),
            ],
        ),
    ]
