# Generated by Django 4.1.3 on 2023-11-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codem", "0007_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="image",
            field=models.ImageField(upload_to="channels"),
        ),
    ]
