# Generated by Django 4.1.3 on 2023-11-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codem", "0009_alter_hackathon_image_alter_tool_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="roadmaps")),
                ("link", models.URLField()),
            ],
        ),
    ]
